---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgA3Hg/xhJw3sECujv4ITLofKkg8D4GhUvUdiKD8yUGxt6TSBHGx9NKwSLuqAfQkXUPlj173n5sLy6D4Ri9Ub3eVkYGLhGrIospU5fgJfoDUoxNK6akNCAZd0c4FHVazhL0zo4dp42GCRDn7p377kazysf60uT1Dgo+VevAETiJWPdxhJ+zMZw2yIO3IU5EUMmGJKllvbfwIMUhwHeEn1Fog3wNMcNMTZ+FQI7qealsfXPfGt5CEE65axl78IXvzVgep4QzgjdDvoegdbQyi3DtvO1I20xGaTpDM/76fjtvT66x9nWs9yIpVAZo5M6ZALpDIe8GpeLACoD/jcIHZ5l3W2FtXnlogtrcQTKgcWOQZTnjOxCI+vHKcKsnhMbDO0NxQzhxN19JkSC8o4HqOm3LhtWDWGoQkxvNimq/hFAQYP/jo+tELJr5ZnxienkbX3PYG95ADClX8y4kWC6q27q+nWbCWx3wKnhA+e6KV8tB7eDnayGZas/W+5+dXPWsJMa7bST5U6EiuC+VAwtipABxhQaSi4KzYb+SIWOia74ejsm7HAhrg9Y/VLSZ6szEWZjYCxDzJ95cUgA9K0y5QF7WjKgWtbZXUG8cwA2Rg5g9vEZdcXdTdr5NHV2mQOvemUXUOy6NpFuNDJ1RU0l+FHmG+uR0zWig/UKHf8SciHgikv90V7X9gdok/dAo2zNSzR9PsnlWgG7F9zpxh5GNm0rctmMUBQ05dnoG3emkCNeK3NeNRr4Pxrs/YiEh+zNVQW3zb8g9TnEVMMFscLB5MgA/JPqeji5yYwbU/DqjufLCrxxyxgHE9gZgq2Dp4P6vsqHyqJRtKFHLVhWO8I4Tn73OrfrIw3jEtvdPR3+jeI3sqUyA/I45hVOlwtTNVmOK2OJH70Xe/z+N0cKGipg+dYcRrkyPSDLU9waQx1AHDrSmCYBTk9krsqfSS
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
