---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgB7kTSpwpl0bNeFrLgfX0Tgfz2KBygNCzyF8M8v1X8gz6UgOY7JUmSd9tmxeREq974umN3F4R8Y1TJtlGCWhFpRXoFVdwJxb5aWIKhZ2z0q6JmdrcrdCopoUQXNgHzAcVMomyUhxDZ2fn88QrIBVRbSzX52p0Q2i3zhHi+Xz+GnXur/6xB7s3mx7vc6HBkFN/Na+IidAgPuGweQ/4jL53+EDygOxkN29ulHPWQO6ESyjK8HugPw8D65fz6ManJHzwe1p9s5xmtv8ffuu22p8hzHxJN/Fgw+9GJS1XskRiUHBPmxRlsH9ypB6lxb4WXlQSdOiJHmLkc+4lEQHsAT/12oPivWOLhxkU2A27DJIKwtmtG+WjcS5op0b+lBua6ukGEjvZb9vYfYL5NLs+tXmL+4jKSwhxOAjVQQl8nzEkF6krqN/xqxDr3LnvwwW4Q0cCo8eBtv+hdS5j9sAdD/PqLvx9h86UTWC7txtyT+C8GI5udzMT8nl7FMLjf7omDuyNWvrtPueaBK9zqz0JFRIaGpH60EoYJD7NR/+9eI+hI6F76YgotO69TMvlm5ACWqRaWb5v6ZMCwQRia0u7XNeOOEDb3i7YV8aqRhooUxQhrrfZy2XXRm6cbj36YioT8lW62e+DAr5j3z4uhYnCkltjs+sMUKnLYMDLo2YUy9DnvSJxmzNM8J6cwFPK7emf4qkSdkpfNS1FqfTbl+hMihhhRav3EgC5HTrj3gVfKiJxZyyL70zB8kqoPOcVLRsY5IMMmh7gUU5wcdf88wJUEmdBE+oTKPDs0P+6+TXOSCa965ulmcAMoD0+76QSXMjna00/Y/zJnPrssT/G8MvLxdnUKJis+I1mwiwd1XrWCSJ9ZbjjVGH8wmMekTc/1apeL1Z8V9kDj1rcW1Um8l2cTj5nhskcpTsPIu2Qx00/gP6nqrGKZArPV35QXM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
