---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgAvzzMG/09VrvdYgzX6eLwKBfUMts5OKydNgG0EiyjUJuUdZd6H1YAMW1OFJwwBj/H5pXQ3D2V3St2ez4IWO7Cx4KpVByYCyRZfeOj41mpPaeu+36vvKdVvyRyIvPMOLLQpZu95yDCLO7UurTXXIeeUz1ZKCK8Z+rOUeIaxj+TfkUdOYcbe5grNiea1f0JP59BZNEb28QHQ+rjQpnAI+Z5X9kum/OLGp4a0qahJeY0SDbh8I+Mo8hLYGIYdgAIAh4nzdJ9Z2C4eLOMwCovlfecLM5DZyJ0BE43KwC5QxgOmR68+l+SFItZODfqglffmvG4F5lTfyGUBDyMZWdMMJi2rglJnpwwKsJsy+xdeuyXnk19v6KR9lc+du46qoqyqbcG0k4qrErD4HHakbP5jz8R06djn37LTPJ/PmncQ0QDl8sSlK6KdCFupG3qynn6SplYNGVoi4XtNBkP+mXWNX8zNNvLypXYhTx1rkKNHruiju3HWxLMGT3b9KajKPunDf7LwMZB2UrsdWX8zrmDbJXrp97ESuSdzI1Q4eRSW8ZlxygkmUpsyQG3Tj/UzeEeFHABW0pANp/JRqmTQIXjo4JoM81G0E7LNn1QjtdPCEr27MGAJN9IY5/4NQ2iWiVj7tmq61o7wkMm/oaKm8Cej+pz/h1oo5V59l3cjPz84e7GGLZqp9w/1wLnWn3rgW0i28sZkPlRTJEvO3BSlXQPSoB/woeMy9fnRpaBgdL/YxEoArs/eAolOnWN+FILR7FadISx8ZsxjCnMa0tglE7vNW7QUDP8tOpYHQYwe0jE3bzQXvQK0ObXhAfpytLwS62Br+bFS0K2G9u4l4Zuh5EyjRBUPcU/RwbRzahJ3FYVh5NDTGbivtFEuPmUu106yvJ9C2003OLlzBwG9QMJVG4dSuMoLxlNLAjwEeHOvQ8p4DauuP6quwm48d2pS
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
