---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBwxlHiGHZMz6gEWZkqAeltlUcVneqVUQExuYUjOSCMyrsljSQQFrcgza/QAph4sj7vkhtJb8zf5cLUZ5LFYwqJmQJu+yEKJri1diOljbaSRnqxOiFMPsvuwyFE3znWow16rcv+CNxmZlKHUJDauTIW1DyUg8NRkIDBjS1ouNw5ilRcgBPUUEK+p9WaBwSLUrOf6ArzXmRJaY9/L+pcSNjgjMzdmO2ybJjaoD8bxWdI3wWk4TNq8Mx2iZuEZSkc/qI9kEsd1lkWoTwVTUxWY0fSSE+0XUslg0DIpnRMZTpj+xt1+V4MLDJmZDNd7XZF6O4g9zkI+YivLTfz6T+A9Bf+rcCrBK4ysddHyRA3VGSn+CJulEeW3KPE6i1aMaQk2ZV20JdyvpZ84xMVp3gRTQcp+tA9w1H9STPG2ZZUyPsT50Yzpe2aXmqcZe92y+sY4Lwa8oIr0HnOFAR2qAo/ZiBxmuZDHWe4G+NwzSSuolVsALrKJyVbuOxKMLh+JU3GOPpbGCzvY1BJX0E99JBYuOCRHuElsEeQAFThqGr4y8+oTH18kC3VbEV28wtRReZXL8tp9+MFmiWdZLUpYb2/rKnpNBWoAGbyxtx3zROtqSyHM99ANrAV2rjR4f/43jXBae+iomJlxCxkOxdnPoyM+RPG3YiM8GjMUijRFF/Zw48CGngBhE3jYmAgcfvtdg18EuCUw6Djtw/GEKJ9
  template:
    metadata:
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
