---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgDGPdUt0v3F1xkBiP6hnfIZ6+Px9SZZgvdi49pb+05QsYClo+VbkFSHZIhoha5Xx9wVWbnIub3OF40F2fFfuBMdvyhHEhlr5rwXOS+FmmuViYYS5VFQhzIv6al4G9JUTVNDzFw8cOGBWSl0X+CgexKRLvv2ZV1jcwKYyu9XEQa+s9rnWxN8eRuZPreuRSqmNAQD9akxwIfW3JF92JhCA7PFjHOMNCeIf9NACiIPFBSUnPTJbmdSkNYlZL9GdHKPU9naT0EWA8az+4qZ7KN6rVtpVxvV2YS3hS7AaiCVaafJtQsz6xcIiQcmX7woRbKJSNMg8vv3bqQDqew4MKM+Dvap6ibwNCGB+CltoxmLCZZGcatHI6Ve/nZHXKc8PcTQ5ow8GGCKrflTQLErzSxgjxzMbf/4vf/dk3+dKWWEY8lly6zWe8dPpK37ZviCYWlLN39GTizDWVF50ly3MkiOY4iDCh6wWGTduSUYHc23hmpgNq4+ep2+clYxkPW8QEMKjzzDqvoBmCUlbZdXmxCBbvQEtgsCwKSaK6B+r3KIWmVT215B7lZlewOIRloXF4XbIpRrKN3+QDujQUlBbGs0eEN0TSapK1wH682GzP846Il7bfmY4SEAu90x08RIJ5CfU9x5G3GWmgn7tJ02nRti2PjmDuWSqKtVpnANIFAVSsyICkC/ZJUduOFH1K17Izv6GGbkzUCfq+56T/6s
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
