---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBRn4x0/e5yFio9ZKvQ19CUp+jJAeCYmf0F+DX86HC46ZxkqLuOUWF+6lzR3YnQZ5LsPNdnakaXLawnCgPFbsA2qnBVEwOM6S9rREeACGpo2WzwPNKAY7tHNYfqPJjuUVnZo8UqWbyyiSF5o8g8VXG/qIQLSAeLq/3b2cZq1S9QNA46tZJITawk+Ym2BNmulKAIf6zcf2NnYMNN5VsfWzFWZQOIJ1V7sGvnWFc7gmCYqMr4MEaFozPfBvoQqIPr6TAinPiAzVPGBdFtM56POslAhFCRDSG6D/lDRIoOWsTICouIdHqgIer2r5z6nQ+voqHJNZkAC104hroeAeEgHnbis51MdhmeGdx5wH1K90i9eYxr/mPFRICXhgAUe1ykbc5Plu+qXrLV5VIP273S03UlpwN5ZymneVwLawkBgZpHmWTwyUV4FOHfksNVqjVcGUKBBFWMhqB5oO5FFNJBbTPyKQJWKveJ8/+6S3L5mGQkqiQsmpwiP/B1JIHlqrD582O2XRaLZJZjR2p0pqqAxi3fhTSMWZ5/l5ui4ZO5A8RDCvZDhn96Aox/sbfXRk7ZQjZkjp1ugknkrjnhwg8W6zz3xgr7s/8CMYKcRcrAl4qDoow9klH+hhvkVbdVeqnWPDFkz2hRgBrZat9bx2Kleb+L4XHys8SjqjpeuMs1eGtBBGlaQoSs3rVu7A6oZf3iIktWFPmeCtfFqqWm
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
