---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-secret
  namespace: navidrome
spec:
  encryptedData:
    password: AgCBG8Vedye2QZzO7j7dDFl9V5nzs8euoABpml27CG2bjVbspmIP26jGiMcSBbqVxgMY6q1/7XNa9wKFiTbI8p8SHEeqse9NE3kcoR7CPfGvft12n8pptMxEUXZ9yulx9r98ZFftMG1ZeOAjhpUPrXW5FIOfLk5IebVPv3MQZABMMLBUGlhm3gcr1uvUVkXqGoY9Forc6enEVXjHyMC53eXhbITMuSK18+7wWgY0vL3d21kXoZ+5jM5dFQKKFZ8L1/5yLuUprK5UW8KbTZzpVzqqFC701fMiz7iCNHUcQvUqP6APWXKt5yllWPFQZaIIe5a5iQqpnPw9x840JZ8m/kGKxLyno4QMkfDYyh/zbKtsp2ufsLxUtsU98PbTB1gNDMs5lEaOC4iTIC82j6WNaKRk8rHIr48qH8l2LpTEc/4FvfTukmDICZERfQjN7ZLiwvcCHv3MrxQ7dhpsh5oSqKipt8VmBGEa8JEl+9ILYJWK297YRKagOtyqoM0QuvCCw8JhmzTDr+SnW4Xa6Wl/TMO19oILDd2foZ6ATnOF5HOd7GLxm8SDOHLi7LTvMR+TU1qlXL2l42xrM8FIJfcrtquCyDp60e8moFQpaFl3glQYOCrw33wJ7ZhnYWZhZQgGoLdhuIGngnC/pPLGR5P6Hkl7sJjuXtL3T9oBBEQ+6ljY8vmZ442xXRdmFCLHFkI3njVFjxbfMuP/WPpz
    username: AgAR1hrMtQ7naIgo7Y6NgluAMbu78hl2CCj5W3W3szOnnB4BZ1JPXPcvwYBINCGAf92pSSAVmc6jTRVZV/0v3DaWBlbQk269RnkGz50olIkKs5SQUrooVvW2Jk8P6gGD39ewv92wDCeFUxZQtHsNeq7w5s5fjkpACOnZ0nQTcOoB/YqoObujN8dVMIQUWEtE3lqs7EKf36bG/1Hp5jSUn57Zt1YhoGaJabPrEFGTY4QvrGQdeHHitaHh9uqoickyPfoJQQNEpqUQslC1svbLHsWfw2vS7Jaj5thxcaH+kYybMEQdrwC09oNrQrINRRLKIozldffaG5jJ7NwDwfDHfR3etITwOUFHYPjFR0hsJuiiXCrQh1+l0DLzrW8kZkjmkVhlLVYb5mtiuaZYcaWjA1l/IbJbfhVdpkrM/D7SN4w1D0Fd21jZJw1M8oXeHSkZo1fcJCyzPcJsrQWDZr83JnCrBqwvv1XhaAx4/Z+DOkTXv3yS6LbacJDP3SuBWMczTeDg44pVzGEg9Fgyi5lo1Bcy4t9cD+wpXSLbdULz3ZhHoMzJz1pVdCkvZFpOFE9EcZT2WngPyTr4oTefYkJegjfQHvmOAFO8ihBQMRTDygCioo846YW2Ph4uA1zbkaIpHjeCnZoaXA/MrQt8SIqXOx7x/Z6n5wHix9Wgle4QJzohODorysUBuqxjQDHOsM7MMnJ/aRFOk9E8JKsQ
  template:
    metadata:
      name: navidrome-secret
      namespace: navidrome
    type: Opaque
