######################################################################################################################################################
# ファイル   : main.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/05/19                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# Ansible handler 定義
- name: restart_containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
