######################################################################################################################################################
# ファイル   : main.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/05/19                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# control_plane phase 分岐
- name: "Load tasks for cp_phase: {{ cp_phase }}"
  ansible.builtin.include_tasks: "{{ cp_phase }}.yml"
  when: not (ansible_check_mode and cp_phase in ['apps_base', 'rook', 'apps_extras'])
