######################################################################################################################################################
# ファイル   : cloudflare-deployment.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# Cloudflare Tunnel 設定
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      containers:
        - name: cloudflare
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(CLOUDFLARE_TOKEN)"
          env:
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CLOUDFLARE_TOKEN
