######################################################################################################################################################
# ファイル   : all.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# 全 host 共通変数
setup_user_home: "{{ '/root' if ansible_user == 'root' else '/home/' ~ ansible_user }}"
repo_root: "{{ setup_user_home }}/Linux"
github_api_version: auto
helm_install_timeout: "10m"
pod_ready_timeout: 300
node_ready_timeout: 180
reboot_timeout: 300
post_reboot_delay: 30
