######################################################################################################################################################
# ファイル   : k8s.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# Kubernetes 共通変数
kubernetes_apt_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
