######################################################################################################################################################
# ファイル   : navidrome-namespace.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# navidrome Namespace 作成
apiVersion: v1
kind: Namespace
metadata:
  name: navidrome
