######################################################################################################################################################
# ファイル   : requirements.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# Ansible collection 要件
collections:
  - name: community.general
    version: ">=9.0.0"
