apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-data-pv
  namespace: navidrome
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: navidrome-data-nfs-storage-class
  nfs:
    server: ubuntu-102.server.com
    path: /mnt/share/kubernetes/navidrome
