######################################################################################################################################################
# ファイル   : main.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/05/19                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# common role 既定値
kubernetes_apt_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
deb_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
reboot_timeout: 300
post_reboot_delay: 30
