######################################################################################################################################################
# ファイル   : os_base.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# OS 基本設定
- name: apt キャッシュを更新
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
- name: 基本パッケージをインストール
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - apt-transport-https
    state: present
