######################################################################################################################################################
# ファイル   : config.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/05/19                 Gamer-Iris   新規作成
#
######################################################################################################################################################
# Greetmate 実行設定
cache:
  expireSeconds: 1800
log:
  rotationIntervalHours: 6
  retentionDays: 7
maintenance:
  cleanupIntervalHours: 24
  cleanupThresholdDays: 90
  syncIntervalSeconds: 1800
default:
  loginMessage: "%s さんがログインしました！"
  logoutMessage: "%s さんがログアウトしました！"
  kickMessage: "%s さんがキックされました！"
  banMessage: "%s さんがBANされました！"
