######################################################################################################################################################
# ファイル   : main.yml
#
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# 【修正履歴】
# V-001      : 2026/06/27                 Gamer-Iris   新規作成
#
######################################################################################################################################################
---
# workers role 既定値
# node_ready_timeout は group_vars/all.yml で定義済み（180s）
# workers role 固有のタイムアウト追加が必要になった場合はここに追加する
